/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/snippets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all snippets
         * @description Returns a list of all code snippets for the authenticated user.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Maximum number of snippets to return */
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of snippets */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SnippetListResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                429: components["responses"]["RateLimited"];
            };
        };
        put?: never;
        /**
         * Create a snippet
         * @description Create a new code snippet.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SnippetCreate"];
                };
            };
            responses: {
                /** @description Snippet created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SnippetResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/snippets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a snippet
         * @description Returns a single snippet by ID.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Resource ID */
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Snippet details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SnippetResponse"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        /**
         * Update a snippet
         * @description Update an existing snippet.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Resource ID */
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SnippetUpdate"];
                };
            };
            responses: {
                /** @description Snippet updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SnippetResponse"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        post?: never;
        /**
         * Delete a snippet
         * @description Soft delete a snippet.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Resource ID */
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Snippet deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nuggets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all nuggets
         * @description Returns a list of all knowledge nuggets for the authenticated user.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Maximum number of nuggets to return */
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of nuggets */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NuggetListResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /**
         * Create a nugget
         * @description Create a new knowledge nugget.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NuggetCreate"];
                };
            };
            responses: {
                /** @description Nugget created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NuggetResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nuggets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a nugget */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Resource ID */
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Nugget details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NuggetResponse"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        /** Update a nugget */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Resource ID */
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NuggetUpdate"];
                };
            };
            responses: {
                /** @description Nugget updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NuggetResponse"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        post?: never;
        /** Delete a nugget */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Resource ID */
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Nugget deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/todos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all todos
         * @description Returns a list of all todo lists for the authenticated user.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Maximum number of todos to return */
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of todos */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TodoListResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create a todo list
         * @description Create a new todo list.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TodoCreate"];
                };
            };
            responses: {
                /** @description Todo created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TodoResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/todos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a todo list */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Resource ID */
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Todo details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TodoResponse"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        /** Update a todo list */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Resource ID */
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TodoUpdate"];
                };
            };
            responses: {
                /** @description Todo updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TodoResponse"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        post?: never;
        /** Delete a todo list */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Resource ID */
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Todo deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ideas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all ideas
         * @description Returns a list of all ideas for the authenticated user.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Maximum number of ideas to return */
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of ideas */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IdeaListResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create an idea
         * @description Create a new idea.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["IdeaCreate"];
                };
            };
            responses: {
                /** @description Idea created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IdeaResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ideas/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an idea */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Resource ID */
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Idea details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IdeaResponse"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        /** Update an idea */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Resource ID */
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["IdeaUpdate"];
                };
            };
            responses: {
                /** @description Idea updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IdeaResponse"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        post?: never;
        /** Delete an idea */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Resource ID */
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Idea deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all tools
         * @description Returns a list of all tools for the authenticated user.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Maximum number of tools to return */
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of tools */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ToolListResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create a tool
         * @description Create a new tool entry.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ToolCreate"];
                };
            };
            responses: {
                /** @description Tool created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ToolResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a tool */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Resource ID */
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Tool details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ToolResponse"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        /** Update a tool */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Resource ID */
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ToolUpdate"];
                };
            };
            responses: {
                /** @description Tool updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ToolResponse"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        post?: never;
        /** Delete a tool */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Resource ID */
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Tool deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all repos
         * @description Returns a list of all repositories for the authenticated user.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Maximum number of repos to return */
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of repos */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RepoListResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create a repo
         * @description Create a new repository entry.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RepoCreate"];
                };
            };
            responses: {
                /** @description Repo created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RepoResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a repo */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Resource ID */
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Repo details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RepoResponse"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        /** Update a repo */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Resource ID */
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RepoUpdate"];
                };
            };
            responses: {
                /** @description Repo updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RepoResponse"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        post?: never;
        /** Delete a repo */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Resource ID */
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Repo deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/travel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List travel locations
         * @description Returns a list of all travel locations for the authenticated user.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Maximum number of locations to return */
                    limit?: number;
                    /** @description Filter by status */
                    status?: "visited" | "want_to_visit" | "lived";
                    /** @description Filter by location type */
                    location_type?: "country" | "city";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of travel locations */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TravelListResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Add a travel location
         * @description Add a new travel location. Use the Countries or Cities endpoints to get the location_id first.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TravelCreate"];
                };
            };
            responses: {
                /** @description Travel location added */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TravelResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/travel/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a travel location */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Resource ID */
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Travel location details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TravelResponse"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        /** Update a travel location */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Resource ID */
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TravelUpdate"];
                };
            };
            responses: {
                /** @description Travel location updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TravelResponse"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        post?: never;
        /** Remove a travel location */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Resource ID */
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Travel location removed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/countries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List countries
         * @description Returns a list of all countries. This is read-only reference data.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Maximum number of countries to return */
                    limit?: number;
                    /** @description Search by country name */
                    search?: string;
                    /** @description Filter by continent */
                    continent?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of countries */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CountryListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/countries/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a country */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Resource ID */
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Country details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CountryResponse"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List cities
         * @description Returns a list of cities. This is read-only reference data.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Maximum number of cities to return */
                    limit?: number;
                    /** @description Search by city name */
                    search?: string;
                    /** @description Filter by country ID */
                    country_id?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of cities */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CityListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cities/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a city */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Resource ID */
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description City details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CityResponse"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload file to Google Drive
         * @description Upload a file directly to your Google Drive.
         *
         *     **Prerequisites:**
         *     - Google account must be connected in the Integrations page
         *     - Google Drive permissions granted during OAuth
         *
         *     **Limits:**
         *     - Maximum file size: 50MB
         *     - Rate limited per API key
         *
         *     **Note:** This endpoint uses a different server URL than the REST API.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /**
                         * Format: binary
                         * @description The file to upload (max 50MB)
                         */
                        file: string;
                        /**
                         * @description Custom file name (defaults to original)
                         * @example My Document.pdf
                         */
                        fileName?: string;
                        /**
                         * @description Google Drive folder ID (defaults to root)
                         * @example 1aBcDeFgHiJkLmNoPqRsTuVwXyZ
                         */
                        folderId?: string;
                        /**
                         * @description MIME type (auto-detected if not provided)
                         * @example application/pdf
                         */
                        mimeType?: string;
                    };
                };
            };
            responses: {
                /** @description File uploaded successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FileUploadResponse"];
                    };
                };
                /** @description Bad request - No file provided or file too large */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Google account not connected */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                429: components["responses"]["RateLimited"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Natural language API
         * @description Send natural language requests to perform complex operations.
         *
         *     The agent can understand context and perform multi-step operations like:
         *     - "Create a snippet for React hooks"
         *     - "Add France as a country I want to visit"
         *     - "Delete my old Python notes"
         *
         *     **Note:** This endpoint uses a different server URL than the REST API.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description Natural language request
                         * @example Create a new snippet called 'React Hooks' with some example code
                         */
                        message: string;
                    };
                };
            };
            responses: {
                /** @description Agent response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: {
                                /**
                                 * @description Agent's natural language response
                                 * @example I've created a new snippet called 'React Hooks'. You can find it in your Snippets page.
                                 */
                                response?: string;
                                /** @description Actions performed by the agent */
                                actions?: {
                                    /** @example createSnippet */
                                    tool?: string;
                                    result?: Record<string, never>;
                                }[];
                            };
                            meta?: components["schemas"]["ResponseMeta"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                429: components["responses"]["RateLimited"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List subscriptions
         * @description Returns a list of all subscriptions for the authenticated user.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Maximum number of subscriptions to return */
                    limit?: number;
                    /** @description Filter by subscription status */
                    status?: "active" | "cancelled";
                    /** @description Filter by category */
                    category?: string;
                    /** @description Filter by usage type */
                    usage_type?: "personal" | "work";
                    /** @description Filter by billing cycle */
                    billing_cycle?: "monthly" | "yearly";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of subscriptions */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SubscriptionListResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                429: components["responses"]["RateLimited"];
            };
        };
        put?: never;
        /**
         * Create a subscription
         * @description Create a new recurring subscription.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "name": "Netflix",
                     *       "amount": 169,
                     *       "currency": "NOK",
                     *       "billing_cycle": "monthly",
                     *       "category": "Entertainment",
                     *       "next_billing_date": "2025-02-15",
                     *       "usage_type": "personal"
                     *     }
                     */
                    "application/json": components["schemas"]["SubscriptionCreate"];
                };
            };
            responses: {
                /** @description Subscription created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SubscriptionResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscriptions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a subscription
         * @description Returns a single subscription by ID.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Resource ID */
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Subscription details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SubscriptionResponse"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        /**
         * Update a subscription
         * @description Update an existing subscription.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Resource ID */
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SubscriptionUpdate"];
                };
            };
            responses: {
                /** @description Subscription updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SubscriptionResponse"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        post?: never;
        /**
         * Delete a subscription
         * @description Soft delete a subscription. Payment history is preserved.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Resource ID */
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Subscription deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscriptions/{id}/mark-paid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark subscription as paid
         * @description Records a payment for the current billing period and advances the next billing date.
         *     Uses the most recent payment's amount/currency if different from the subscription's base values.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Resource ID */
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Payment recorded and billing date advanced */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MarkPaidResponse"];
                    };
                };
                /** @description No billing date set for this subscription */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscriptions/{id}/backfill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Backfill payment history
         * @description Generate historical payment records for past billing periods.
         *     Useful for importing subscription history or fixing gaps in payment tracking.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Resource ID */
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "periods": [
                     *         "2024-01",
                     *         "2024-02",
                     *         "2024-03"
                     *       ],
                     *       "amount": 169,
                     *       "currency": "NOK",
                     *       "usage_type": "personal",
                     *       "overwrite_existing": false
                     *     }
                     */
                    "application/json": components["schemas"]["BackfillRequest"];
                };
            };
            responses: {
                /** @description Backfill completed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BackfillResponse"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscriptions/{id}/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List payments for a subscription
         * @description Returns all payment records for a specific subscription.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Maximum number of payments to return */
                    limit?: number;
                };
                header?: never;
                path: {
                    /** @description Resource ID */
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of payments */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SubscriptionPaymentListResponse"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscription-payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all subscription payments
         * @description Returns payment records across all subscriptions.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Maximum number of payments to return */
                    limit?: number;
                    /** @description Filter by subscription ID */
                    subscription_id?: string;
                    /** @description Filter by payment status */
                    status?: "paid" | "pending" | "skipped";
                    /** @description Filter by usage type */
                    usage_type?: "personal" | "work";
                    /** @description Filter by payment source */
                    source?: "manual" | "backfilled" | "mark_paid" | "monthly_generation";
                    /** @description Filter payments from this date (inclusive) */
                    date_from?: string;
                    /** @description Filter payments up to this date (inclusive) */
                    date_to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of payments */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SubscriptionPaymentListResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                429: components["responses"]["RateLimited"];
            };
        };
        put?: never;
        /**
         * Create a payment record
         * @description Manually create a payment record for a subscription.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "subscription_id": "123e4567-e89b-12d3-a456-426614174000",
                     *       "payment_date": "2025-01-15",
                     *       "amount": 169,
                     *       "currency": "NOK",
                     *       "status": "paid"
                     *     }
                     */
                    "application/json": components["schemas"]["SubscriptionPaymentCreate"];
                };
            };
            responses: {
                /** @description Payment created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SubscriptionPaymentResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscription-payments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a payment
         * @description Returns a single payment record by ID.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Resource ID */
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Payment details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SubscriptionPaymentResponse"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        /**
         * Update a payment
         * @description Update an existing payment record.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Resource ID */
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SubscriptionPaymentUpdate"];
                };
            };
            responses: {
                /** @description Payment updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SubscriptionPaymentResponse"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        post?: never;
        /**
         * Delete a payment
         * @description Permanently deletes a payment record.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Resource ID */
                    id: components["parameters"]["ResourceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Payment deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ResponseMeta: {
            /**
             * Format: date-time
             * @example 2025-01-01T00:00:00.000Z
             */
            timestamp?: string;
        };
        SuccessResponse: {
            /** @example true */
            success?: boolean;
            data?: {
                /** @example Operation completed successfully */
                message?: string;
            };
            meta?: components["schemas"]["ResponseMeta"];
        };
        ErrorResponse: {
            /** @example false */
            success?: boolean;
            /** @example Error message */
            error?: string;
            meta?: components["schemas"]["ResponseMeta"];
        };
        Snippet: {
            /** Format: uuid */
            id?: string;
            /** @example React useEffect Hook */
            name?: string;
            /** @example Example of useEffect with cleanup */
            description?: string;
            /**
             * @example useEffect(() => {
             *       // effect
             *       return () => cleanup();
             *     }, [deps]);
             */
            code?: string;
            /** @example typescript */
            language?: string;
            /**
             * @example [
             *       "react",
             *       "hooks"
             *     ]
             */
            tags?: string[];
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        SnippetCreate: {
            /** @example React useEffect Hook */
            name: string;
            /** @example Example of useEffect with cleanup */
            description: string;
            /**
             * @example useEffect(() => {
             *       // effect
             *       return () => cleanup();
             *     }, [deps]);
             */
            code: string;
            /** @example typescript */
            language: string;
            /**
             * @example [
             *       "react",
             *       "hooks"
             *     ]
             */
            tags?: string[];
        };
        SnippetUpdate: {
            name?: string;
            description?: string;
            code?: string;
            language?: string;
            tags?: string[];
        };
        SnippetResponse: {
            /** @example true */
            success?: boolean;
            data?: {
                snippet?: components["schemas"]["Snippet"];
            };
            meta?: components["schemas"]["ResponseMeta"];
        };
        SnippetListResponse: {
            /** @example true */
            success?: boolean;
            data?: {
                /** @example 25 */
                count?: number;
                items?: components["schemas"]["Snippet"][];
            };
            meta?: components["schemas"]["ResponseMeta"];
        };
        Nugget: {
            /** Format: uuid */
            id?: string;
            /** @example TypeScript Best Practices */
            name?: string;
            /** @example Notes on TypeScript patterns */
            description?: string;
            /** @example Always use strict mode... */
            content?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        NuggetCreate: {
            name: string;
            description: string;
            content: string;
        };
        NuggetUpdate: {
            name?: string;
            description?: string;
            content?: string;
        };
        NuggetResponse: {
            success?: boolean;
            data?: {
                nugget?: components["schemas"]["Nugget"];
            };
            meta?: components["schemas"]["ResponseMeta"];
        };
        NuggetListResponse: {
            success?: boolean;
            data?: {
                count?: number;
                items?: components["schemas"]["Nugget"][];
            };
            meta?: components["schemas"]["ResponseMeta"];
        };
        Todo: {
            /** Format: uuid */
            id?: string;
            /** @example Weekly Tasks */
            name?: string;
            /** @example Tasks for this week */
            description?: string;
            /**
             * @example - [ ] Review PRs
             *     - [ ] Update docs
             */
            content?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        TodoCreate: {
            name: string;
            description: string;
            content: string;
        };
        TodoUpdate: {
            name?: string;
            description?: string;
            content?: string;
        };
        TodoResponse: {
            success?: boolean;
            data?: {
                todo?: components["schemas"]["Todo"];
            };
            meta?: components["schemas"]["ResponseMeta"];
        };
        TodoListResponse: {
            success?: boolean;
            data?: {
                count?: number;
                items?: components["schemas"]["Todo"][];
            };
            meta?: components["schemas"]["ResponseMeta"];
        };
        Idea: {
            /** Format: uuid */
            id?: string;
            /** @example App Redesign */
            name?: string;
            /** @example Ideas for improving the UI... */
            content?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        IdeaCreate: {
            name: string;
            content: string;
        };
        IdeaUpdate: {
            name?: string;
            content?: string;
        };
        IdeaResponse: {
            success?: boolean;
            data?: {
                idea?: components["schemas"]["Idea"];
            };
            meta?: components["schemas"]["ResponseMeta"];
        };
        IdeaListResponse: {
            success?: boolean;
            data?: {
                count?: number;
                items?: components["schemas"]["Idea"][];
            };
            meta?: components["schemas"]["ResponseMeta"];
        };
        Tool: {
            /** Format: uuid */
            id?: string;
            /** @example VS Code */
            name?: string;
            /**
             * Format: uri
             * @example https://code.visualstudio.com
             */
            url?: string;
            /** @example Development */
            category?: string;
            /** @example Code editor by Microsoft */
            description?: string;
            /** @example 5 */
            rating?: number;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        ToolCreate: {
            name: string;
            /** Format: uri */
            url?: string;
            category?: string;
            description?: string;
            rating?: number;
        };
        ToolUpdate: {
            name?: string;
            url?: string;
            category?: string;
            description?: string;
            rating?: number;
        };
        ToolResponse: {
            success?: boolean;
            data?: {
                tool?: components["schemas"]["Tool"];
            };
            meta?: components["schemas"]["ResponseMeta"];
        };
        ToolListResponse: {
            success?: boolean;
            data?: {
                count?: number;
                items?: components["schemas"]["Tool"][];
            };
            meta?: components["schemas"]["ResponseMeta"];
        };
        Repo: {
            /** Format: uuid */
            id?: string;
            /** @example my-awesome-project */
            title?: string;
            /** @example A brief description of the project */
            summary?: string;
            /**
             * @example # My Project
             *
             *     Detailed description...
             */
            description_md?: string;
            /**
             * Format: uri
             * @example https://github.com/user/repo
             */
            repo_url?: string;
            /**
             * @example github
             * @enum {string}
             */
            source_type?: "github" | "manual";
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        RepoCreate: {
            title: string;
            summary?: string;
            description_md?: string;
            /** Format: uri */
            repo_url?: string;
            /**
             * @default manual
             * @enum {string}
             */
            source_type: "github" | "manual";
        };
        RepoUpdate: {
            title?: string;
            summary?: string;
            description_md?: string;
            repo_url?: string;
            source_type?: string;
        };
        RepoResponse: {
            success?: boolean;
            data?: {
                repo?: components["schemas"]["Repo"];
            };
            meta?: components["schemas"]["ResponseMeta"];
        };
        RepoListResponse: {
            success?: boolean;
            data?: {
                count?: number;
                items?: components["schemas"]["Repo"][];
            };
            meta?: components["schemas"]["ResponseMeta"];
        };
        TravelLocation: {
            /** Format: uuid */
            id?: string;
            /**
             * Format: uuid
             * @description ID of the country or city
             */
            location_id?: string;
            /** @enum {string} */
            location_type?: "country" | "city";
            /**
             * @description Name of the country or city
             * @example France
             */
            location_name?: string;
            /** @enum {string} */
            status?: "visited" | "want_to_visit" | "lived";
            /** Format: date */
            date_from?: string;
            /** Format: date */
            date_to?: string;
            notes?: string;
            is_favorite?: boolean;
            /** Format: date-time */
            created_at?: string;
        };
        TravelCreate: {
            /**
             * Format: uuid
             * @description UUID from Countries or Cities endpoint
             */
            location_id: string;
            /** @enum {string} */
            location_type: "country" | "city";
            /** @enum {string} */
            status: "visited" | "want_to_visit" | "lived";
            /**
             * Format: date
             * @example 2024-06-01
             */
            date_from?: string;
            /**
             * Format: date
             * @example 2024-06-15
             */
            date_to?: string;
            /** @example Amazing trip! */
            notes?: string;
            /** @default false */
            is_favorite: boolean;
        };
        TravelUpdate: {
            /** @enum {string} */
            status?: "visited" | "want_to_visit" | "lived";
            /** Format: date */
            date_from?: string;
            /** Format: date */
            date_to?: string;
            notes?: string;
            is_favorite?: boolean;
        };
        TravelResponse: {
            success?: boolean;
            data?: {
                travel?: components["schemas"]["TravelLocation"];
            };
            meta?: components["schemas"]["ResponseMeta"];
        };
        TravelListResponse: {
            success?: boolean;
            data?: {
                count?: number;
                items?: components["schemas"]["TravelLocation"][];
            };
            meta?: components["schemas"]["ResponseMeta"];
        };
        Country: {
            /** Format: uuid */
            id?: string;
            /** @example France */
            name?: string;
            /** @example FR */
            iso_code?: string;
            /** @example Europe */
            continent?: string;
        };
        CountryResponse: {
            success?: boolean;
            data?: {
                country?: components["schemas"]["Country"];
            };
            meta?: components["schemas"]["ResponseMeta"];
        };
        CountryListResponse: {
            success?: boolean;
            data?: {
                count?: number;
                items?: components["schemas"]["Country"][];
            };
            meta?: components["schemas"]["ResponseMeta"];
        };
        City: {
            /** Format: uuid */
            id?: string;
            /** @example Paris */
            name?: string;
            /** Format: uuid */
            country_id?: string;
            population_rank?: number;
            countries?: {
                /** @example France */
                name?: string;
                /** @example FR */
                iso_code?: string;
            };
        };
        CityResponse: {
            success?: boolean;
            data?: {
                city?: components["schemas"]["City"];
            };
            meta?: components["schemas"]["ResponseMeta"];
        };
        CityListResponse: {
            success?: boolean;
            data?: {
                count?: number;
                items?: components["schemas"]["City"][];
            };
            meta?: components["schemas"]["ResponseMeta"];
        };
        FileUploadResponse: {
            /** @example true */
            success?: boolean;
            data?: {
                /**
                 * @description Google Drive file ID
                 * @example 1aBcDeFgHiJkLmNoPqRsTuVwXyZ
                 */
                fileId?: string;
                /** @example My Document.pdf */
                fileName?: string;
                /** @example application/pdf */
                mimeType?: string;
                /**
                 * @description File size in bytes
                 * @example 1024567
                 */
                size?: string;
                /**
                 * Format: uri
                 * @description Shareable view link
                 * @example https://drive.google.com/file/d/1aBcDeFgHiJkLmNoPqRsTuVwXyZ/view
                 */
                webViewLink?: string;
                /**
                 * Format: uri
                 * @description Direct download link
                 * @example https://drive.google.com/uc?id=1aBcDeFgHiJkLmNoPqRsTuVwXyZ&export=download
                 */
                webContentLink?: string;
            };
            meta?: components["schemas"]["ResponseMeta"];
        };
        Subscription: {
            /** Format: uuid */
            id?: string;
            /** @example Netflix */
            name?: string;
            /** @example Entertainment */
            category?: string;
            /** @example 169 */
            amount?: number;
            /** @example NOK */
            currency?: string;
            /**
             * @example monthly
             * @enum {string}
             */
            billing_cycle?: "monthly" | "yearly";
            /**
             * Format: date
             * @example 2023-01-15
             */
            start_date?: string;
            /**
             * Format: date
             * @example 2025-02-15
             */
            next_billing_date?: string;
            /** @example Credit Card */
            payment_method?: string;
            /**
             * @example personal
             * @enum {string}
             */
            usage_type?: "personal" | "work";
            /**
             * @example active
             * @enum {string}
             */
            status?: "active" | "cancelled";
            /** Format: date-time */
            cancelled_at?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        SubscriptionCreate: {
            /** @example Netflix */
            name: string;
            /** @example 169 */
            amount: number;
            /** @example NOK */
            currency: string;
            /** @enum {string} */
            billing_cycle: "monthly" | "yearly";
            /** @example Entertainment */
            category?: string;
            /** Format: date */
            start_date?: string;
            /** Format: date */
            next_billing_date?: string;
            payment_method?: string;
            /**
             * @default personal
             * @enum {string}
             */
            usage_type: "personal" | "work";
        };
        SubscriptionUpdate: {
            name?: string;
            category?: string;
            amount?: number;
            currency?: string;
            /** @enum {string} */
            billing_cycle?: "monthly" | "yearly";
            /** Format: date */
            start_date?: string;
            /** Format: date */
            next_billing_date?: string;
            payment_method?: string;
            /** @enum {string} */
            usage_type?: "personal" | "work";
            /** @enum {string} */
            status?: "active" | "cancelled";
        };
        SubscriptionResponse: {
            success?: boolean;
            data?: {
                subscription?: components["schemas"]["Subscription"];
            };
            meta?: components["schemas"]["ResponseMeta"];
        };
        SubscriptionListResponse: {
            success?: boolean;
            data?: {
                count?: number;
                items?: components["schemas"]["Subscription"][];
            };
            meta?: components["schemas"]["ResponseMeta"];
        };
        MarkPaidResponse: {
            success?: boolean;
            data?: {
                success?: boolean;
                /** @example Marked as paid for 2025-01-15 */
                message?: string;
                /**
                 * Format: date
                 * @example 2025-02-15
                 */
                new_next_billing_date?: string;
            };
            meta?: components["schemas"]["ResponseMeta"];
        };
        BackfillRequest: {
            /**
             * @description Array of billing periods. Monthly: YYYY-MM format, Yearly: YYYY format
             * @example [
             *       "2024-01",
             *       "2024-02",
             *       "2024-03"
             *     ]
             */
            periods: string[];
            /** @example 169 */
            amount: number;
            /** @example NOK */
            currency: string;
            /** @enum {string} */
            usage_type?: "personal" | "work";
            /**
             * @description If true, overwrites existing payments for these periods
             * @default false
             */
            overwrite_existing: boolean;
        };
        BackfillResponse: {
            success?: boolean;
            data?: {
                success?: boolean;
                /** @example Backfill complete: 3 created, 0 overwritten, 1 skipped */
                message?: string;
                /** @example 3 */
                created?: number;
                /** @example 0 */
                overwritten?: number;
                /** @example 1 */
                skipped?: number;
            };
            meta?: components["schemas"]["ResponseMeta"];
        };
        SubscriptionPayment: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            subscription_id?: string;
            /**
             * Format: date
             * @example 2025-01-15
             */
            payment_date?: string;
            /** @example 169 */
            amount?: number;
            /** @example NOK */
            currency?: string;
            /**
             * @example paid
             * @enum {string}
             */
            status?: "paid" | "pending" | "skipped";
            /**
             * @example personal
             * @enum {string}
             */
            usage_type?: "personal" | "work";
            /**
             * @example manual
             * @enum {string}
             */
            source?: "manual" | "backfilled" | "mark_paid" | "monthly_generation";
            notes?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        SubscriptionPaymentCreate: {
            /** Format: uuid */
            subscription_id: string;
            /** Format: date */
            payment_date: string;
            amount: number;
            currency: string;
            /**
             * @default paid
             * @enum {string}
             */
            status: "paid" | "pending" | "skipped";
            /** @enum {string} */
            usage_type?: "personal" | "work";
            notes?: string;
        };
        SubscriptionPaymentUpdate: {
            amount?: number;
            currency?: string;
            /** @enum {string} */
            status?: "paid" | "pending" | "skipped";
            /** @enum {string} */
            usage_type?: "personal" | "work";
            notes?: string;
        };
        SubscriptionPaymentResponse: {
            success?: boolean;
            data?: {
                payment?: components["schemas"]["SubscriptionPayment"];
            };
            meta?: components["schemas"]["ResponseMeta"];
        };
        SubscriptionPaymentListResponse: {
            success?: boolean;
            data?: {
                count?: number;
                items?: components["schemas"]["SubscriptionPayment"][];
            };
            meta?: components["schemas"]["ResponseMeta"];
        };
    };
    responses: {
        /** @description Unauthorized - Invalid or missing API key */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "success": false,
                 *       "error": "Invalid or missing API key",
                 *       "meta": {
                 *         "timestamp": "2025-01-01T00:00:00.000Z"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "success": false,
                 *       "error": "Resource not found",
                 *       "meta": {
                 *         "timestamp": "2025-01-01T00:00:00.000Z"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Bad request - Invalid input */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Rate limit exceeded */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "success": false,
                 *       "error": "Rate limit exceeded: 100 requests per hour. Try again in 23 minutes.",
                 *       "meta": {
                 *         "timestamp": "2025-01-01T00:00:00.000Z"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description Resource ID */
        ResourceId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
